JimdoJimFlow\PrintTicketBundle_tickettype:
  resource: "@JimdoJimFlowPrintTicketBundle/Resources/config/routing/tickettype.yml"
  prefix:   /admin/tickettype

JimdoJimFlow\PrintTicketBundle_printer_config:
  resource: "@JimdoJimFlowPrintTicketBundle/Resources/config/routing/printer.yml"
  prefix:   /admin/printer

JimdoJimFlow\PrintTicketBundle_template:
  resource: "@JimdoJimFlowPrintTicketBundle/Resources/config/routing/template.yml"
  prefix:   /template

JimdoJimFlow\PrintTicketBundle_print:
  resource: "@JimdoJimFlowPrintTicketBundle/Resources/config/routing/print.yml"
  prefix:   /print

JimdoJimFlow\PrintTicketBundle_print_buttons:
  resource: "@JimdoJimFlowPrintTicketBundle/Resources/config/routing/print-buttons.yml"
  prefix:   /buttons

